[package]
name = "cli"
version = "1.0.0"
edition = "2021"
authors = ["Samuel Oliveira <samuel@beasync.com>"]

[[bin]]
name = "pvm"
path = "src/main.rs"

[dependencies]
lenaris = { path = "../lenaris" }